ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/USB0              # ✅ 修正済み
    baudrate: 512000                # ✅ 修正済み（TG15に必須）
    frame_id: laser_frame
    ignore_array: "150, 180, -180, -150"
    angle_max: 180.0
    angle_min: -180.0
    range_max: 16.0
    range_min: 0.1
    auto_reconnect: true
    resolution_fixed: true
    reversion: false
    fixed_resolution: true
    exposure: false
    heartbeat: false
    scan_frequency: 10.0
    sample_rate: 20
    lidar_type: 1
    device_type: 0

